home/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'home'

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/home.html'), name='home'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

sunrise_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from sunrise_project import settings


urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('shop/', include('products.urls', namespace='shop')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    # login
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # password change
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done')),
         name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done'),
                                                                 email_template_name='registration/password_reset_email.html'),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('register/', views.register, name='register'),
    path('account/<int:id>/', views.profile_detail, name='user_detail'),
    path('edit/', views.edit, name='edit')
]

home/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, default='default.png')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

users/models.py
# from django.db import models
# from django.conf import settings
#
#
# class Profile(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     date_of_birth = models.DateField(blank=True, null=True)
#     photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
#
#     def __str__(self):
#         return 'Profile for user {}'.format(self.user.username)

users/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(help_text='Логин')
    password = forms.CharField(widget=forms.PasswordInput)


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data

        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

home/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'products/product_list.html', {'category': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request, 'products/product_detail.html', {'product': product})

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse

from .forms import LoginForm, UserRegistrationForm, UserEditForm


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Создаем нового пользователя, но пока не сохраняем в базу данных.
            new_user = user_form.save(commit=False)
            # Задаем пользователю зашифрованный пароль.
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request,
                          'registration/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})


def profile_detail(request, id):
    user = get_object_or_404(User, id=id)
    return render(request, 'registration/user_detail.html', {'user': user})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
    return render(request, 'registration/edit.html',
                  {'user_form': user_form})

templates/home/base.html
{%  load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}SunShop{% endblock %}</title>
</head>
<body>

<header class="header">
    <div class="container">
        <div class="header-top">
            <h1><a href="{% url 'home:home' %}" class="logo">SunShop</a></h1>
            <nav class="main-nav">
                <ul>
                    <li><a href="#" class="heart">желаемое</a></li>
                    <li><a href="#">корзина</a></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'users:user_detail' user.id %}">профиль</a></li>
                        <li><a href="{% url 'users:logout' %}">выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}">войти/регистрация</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <div class="header-bottom">
            <nav class="nav">
                <ul>
                    <li><a href="#">акции</a></li>
                    <li><a href="#">новинки</a></li>
                    <li><a href="#">лидеры продаж</a></li>
                    <li><a href="#">в кредит и рассрочку</a></li>
                    <li><a href="#">продавай</a></li>
                    <li><a href="#">рекламируйся</a></li>
                    <li><a href="#">истоия просмотров</a></li>
                    <li><a href="#">все продавцы</a></li>
                    <li><a href="#">контакты</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

<div class="container">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

{% block content %}

{% endblock %}

<footer class="footer">
    <div class="container">
        <div class="info-block">
            <div class="info">
                <span>Делаем доставку в любой регион</span>
                <p><strong>Адрес для физических писем от клиентов:</strong>
                    Кыргызстан, г. Бишкек <strong>720000</strong>
                    проспект <strong>Чуй 96</strong>
                    Абонентский ящик: <strong>2020</strong>
                    Организация: <strong>маркетплейс Svetofor</strong></p>
            </div>
            <div class="info">
                <span>Продавцам</span>
                <ul>
                    <li><a href="#">Станьте нашим партнером</a></li>
                    <li><a href="#">Рекламируй с нами</a></li>
                </ul>
            </div>
            <div class="info">
                <span>Покупателям</span>
                <ul>
                    <li><a href="#">оплата</a></li>
                    <li><a href="#">доставка</a></li>
                    <li><a href="#">кредит и рассрочка</a></li>
                    <li><a href="#">обмен и возврат</a></li>
                    <li><a href="#">гарантия</a></li>
                    <li><a href="#">регистрация</a></li>
                    <li><a href="#">как оформить заказ</a></li>
                    <li><a href="#">установка техники</a></li>
                    <li><a href="#">оцените качество обслуживания</a></li>
                </ul>
            </div>
            <div class="info">
                <span>О нас</span>
                <ul>
                    <li><a href="#">Контакты</a></li>
                    <li><a href="#">Корпоративным клиентам</a></li>
                    <li><a href="#">вакансии</a></li>
                    <li><a href="#">пользовательское соглашение</a></li>
                    <li><a href="#">сравнить кредиты банков</a></li>
                    <li><a href="#">о компании</a></li>
                </ul>
            </div>
        </div>
        <p class="footer-bottom">интернет магазин SunShop 2021-2031</p>
    </div>
</footer>
</body>
</html>

templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
    <div class="banners">
        <div class="container">
            <img src="" alt="" width="800" height="300">
        </div>
    </div>

    <div class="container">
        <div class="grid">
            <div class="right-side">
                <h4 class="title-h4">Весь каталог</h4>
                <ul>
                    {% for category in product_category_context %}
                        <li><a href="{% url 'shop:product_list_by_category' category.slug %}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="left-side">
                <div class="low-prices-block">
                    <h4 class="title-h4">Последние товары</h4>
                    <div class="low-prices">
                        {% for product in product_context %}
                            <div class="remize">
                                <img src="{{ product.image.url }}" alt="">
                                <h6><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>
                                <p>{{ product.price }}</p>
                            </div>
                        {% endfor %}
                        <a href="{% url 'shop:product_list' %}" class="more-info">подробнее</a>
                    </div>
                </div>
                <div class="best-items-block">
                    <h4 class="title-h4">Лучшие товары месяца</h4>
                    <div class="best-items">
                        <div class="best-item">
                            <img src="" alt="">
                            <h6><a href="#">Имя товара</a></h6>
                            <p>цена товара</p>
                        </div>
                        <div class="best-item">
                            <img src="" alt="">
                            <h6><a href="#">Имя товара</a></h6>
                            <p>цена товара</p>
                        </div>
                        <div class="best-item">
                            <img src="" alt="">
                            <h6><a href="#">Имя товара</a></h6>
                            <p>цена товара</p>
                        </div>
                        <div class="best-item">
                            <img src="" alt="">
                            <h6><a href="#">Имя товара</a></h6>
                            <p>цена товара</p>
                        </div>
                        <div class="best-item">
                            <img src="" alt="">
                            <h6><a href="#">Имя товара</a></h6>
                            <p>цена товара</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/products/product_detail.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="grid">
            <div class="right-side">
                <h4 class="title-h4">Весь каталог</h4>
                <ul>
                    {% for category in product_category_context %}
                        <li><a href="{% url 'shop:product_list_by_category' category.slug %}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="left-side">
                <div class="product-detail">
                    <h1>{{ product.name }}</h1>
                    <h2>
                        <a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
                    </h2>
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "images/default.png" %}{% endif %}">
                    <p class="price">${{ product.price }}</p>
                    {{ product.description|linebreaks }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/products/product_list.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Список товаров{% endblock %}

{% block content %}
    <div class="container">
        <div class="grid">

            <div class="right-side">
                <h4 class="title-h4">Весь каталог</h4>
                <ul>
                    <li {% if not category %}class="selected"{% endif %}>
                        <a href="{% url "shop:product_list" %}">Все</a>
                    </li>
                    {% for c in categories %}
                        <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="left-side">
                <div id="main" class="product-list">
                    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
                    {% for product in products %}
                        <div class="item">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "images/default.png" %}{% endif %}">
                            </a>
                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            <br>
                            ${{ product.price }}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}